version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: family-app-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - family-app-network
  
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: family-app-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
    networks:
      - family-app-network

networks:
  family-app-network:
    driver: bridge 